services:
    app.markdown:
        class: Revolter\IdealistBundle\Utils\Markdown
    app.twig.app_extension:
        class:     Revolter\IdealistBundle\Twig\AppExtension
        arguments: ['@app.markdown']
        public:    false
        tags:
            - { name: twig.extension }
#    revolter_idealist.example:
#        class: Revolter\IdealistBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
